/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ContentBody = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & MediaItem>;

export type Metric = {
  _type: "metric";
  value: string;
  label: string;
  note?: string;
};

export type MediaItem = {
  _type: "mediaItem";
  kind: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  videoFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  poster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  caption?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  gridOrder?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  tickerItems?: Array<string>;
  contactEmail?: string;
  locations?: Array<string>;
  social?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
};

export type Musing = {
  _id: string;
  _type: "musing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt?: string;
  excerpt?: string;
  tags?: Array<string>;
  body?: ContentBody;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  client?: string;
  year?: number;
  tags?: Array<string>;
  heroMedia?: MediaItem;
  body?: ContentBody;
  gallery?: Array<{
    _key: string;
  } & MediaItem>;
  featured?: boolean;
  order?: number;
  publishingStatus?: "drafted" | "framed" | "sketch" | "name-only";
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  standfirst?: string;
  client?: string;
  role?: string;
  sector?: string;
  timeframe?: string;
  year?: number;
  tags?: Array<string>;
  heroMedia?: MediaItem;
  metrics?: Array<{
    _key: string;
  } & Metric>;
  body?: ContentBody;
  gallery?: Array<{
    _key: string;
  } & MediaItem>;
  featured?: boolean;
  order?: number;
  publishingStatus?: "drafted" | "framed" | "sketch" | "name-only";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ContentBody | Metric | MediaItem | SiteSettings | Musing | Slug | Project | CaseStudy | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "settings": *[_id == "siteSettings"][0]{    title,    intro  },  "ordered": *[_id == "siteSettings"][0].gridOrder[]->{    _id,    _type,    title,    "slug": slug.current,    tags,    client,    year,    "subtitle": select(      _type == "caseStudy" => coalesce(sector, client, role),      coalesce(client, description)    ),    "summary": coalesce(standfirst, description),    heroMedia{      kind,      alt,      image,      poster,      "videoUrl": coalesce(videoUrl, videoFile.asset->url),      "lqip": image.asset->metadata.lqip    }  },  "extra": *[    (_type == "caseStudy" || _type == "project")    && defined(slug.current)    && !(_id in *[_id == "siteSettings"][0].gridOrder[]._ref)  ] | order(coalesce(order, 100) asc, coalesce(year, 0) desc){    _id,    _type,    title,    "slug": slug.current,    tags,    client,    year,    "subtitle": select(      _type == "caseStudy" => coalesce(sector, client, role),      coalesce(client, description)    ),    "summary": coalesce(standfirst, description),    heroMedia{      kind,      alt,      image,      poster,      "videoUrl": coalesce(videoUrl, videoFile.asset->url),      "lqip": image.asset->metadata.lqip    }  }}
export type HOME_QUERYResult = {
  settings: {
    title: string;
    intro: null;
  } | {
    title: string | null;
    intro: null;
  } | {
    title: string | null;
    intro: string | null;
  } | null;
  ordered: Array<{
    _id: string;
    _type: "caseStudy";
    title: string;
    slug: string;
    tags: Array<string> | null;
    client: string | null;
    year: number | null;
    subtitle: string | null;
    summary: string | null;
    heroMedia: {
      kind: "image" | "video";
      alt: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      videoUrl: string | null;
      lqip: string | null;
    } | null;
  } | {
    _id: string;
    _type: "project";
    title: string;
    slug: string;
    tags: Array<string> | null;
    client: string | null;
    year: number | null;
    subtitle: string | null;
    summary: string | null;
    heroMedia: {
      kind: "image" | "video";
      alt: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      videoUrl: string | null;
      lqip: string | null;
    } | null;
  }> | null;
  extra: Array<{
    _id: string;
    _type: "caseStudy";
    title: string;
    slug: string;
    tags: Array<string> | null;
    client: string | null;
    year: number | null;
    subtitle: string | null;
    summary: string | null;
    heroMedia: {
      kind: "image" | "video";
      alt: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      videoUrl: string | null;
      lqip: string | null;
    } | null;
  } | {
    _id: string;
    _type: "project";
    title: string;
    slug: string;
    tags: Array<string> | null;
    client: string | null;
    year: number | null;
    subtitle: string | null;
    summary: string | null;
    heroMedia: {
      kind: "image" | "video";
      alt: string;
      image: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      poster: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      videoUrl: string | null;
      lqip: string | null;
    } | null;
  }>;
};
// Variable: WORK_ORDER_QUERY
// Query: {  "ordered": *[_id == "siteSettings"][0].gridOrder[]->{    _type,    title,    "slug": slug.current  },  "extra": *[    (_type == "caseStudy" || _type == "project")    && defined(slug.current)    && !(_id in *[_id == "siteSettings"][0].gridOrder[]._ref)  ] | order(coalesce(order, 100) asc, coalesce(year, 0) desc){    _type,    title,    "slug": slug.current  }}
export type WORK_ORDER_QUERYResult = {
  ordered: Array<{
    _type: "caseStudy";
    title: string;
    slug: string;
  } | {
    _type: "project";
    title: string;
    slug: string;
  }> | null;
  extra: Array<{
    _type: "caseStudy";
    title: string;
    slug: string;
  } | {
    _type: "project";
    title: string;
    slug: string;
  }>;
};
// Variable: WORK_SLUGS_QUERY
// Query: *[(_type == "caseStudy" || _type == "project") && defined(slug.current)]{    "slug": slug.current  }
export type WORK_SLUGS_QUERYResult = Array<{
  slug: string;
}>;
// Variable: WORK_QUERY
// Query: *[(_type == "caseStudy" || _type == "project") && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,    standfirst,    description,    client,    role,    sector,    timeframe,    year,    tags,    heroMedia{      kind,      alt,      caption,      image,      poster,      "videoUrl": coalesce(videoUrl, videoFile.asset->url),      "lqip": image.asset->metadata.lqip    },    metrics[]{      _key,      value,      label,      note    },    body[]{      ...,      _type == "mediaItem" => {        ...,        "videoUrl": coalesce(videoUrl, videoFile.asset->url),        "lqip": image.asset->metadata.lqip      }    },    gallery[]{      _key,      kind,      alt,      caption,      image,      poster,      "videoUrl": coalesce(videoUrl, videoFile.asset->url),      "lqip": image.asset->metadata.lqip    }  }
export type WORK_QUERYResult = {
  _id: string;
  _type: "caseStudy";
  title: string;
  slug: string;
  standfirst: string | null;
  description: null;
  client: string | null;
  role: string | null;
  sector: string | null;
  timeframe: string | null;
  year: number | null;
  tags: Array<string> | null;
  heroMedia: {
    kind: "image" | "video";
    alt: string;
    caption: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    videoUrl: string | null;
    lqip: string | null;
  } | null;
  metrics: Array<{
    _key: string;
    value: string;
    label: string;
    note: string | null;
  }> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "mediaItem";
    kind: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    videoFile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    videoUrl: string | null;
    poster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt: string;
    caption?: string;
    lqip: string | null;
  }> | null;
  gallery: Array<{
    _key: string;
    kind: "image" | "video";
    alt: string;
    caption: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    videoUrl: string | null;
    lqip: string | null;
  }> | null;
} | {
  _id: string;
  _type: "project";
  title: string;
  slug: string;
  standfirst: null;
  description: string | null;
  client: string | null;
  role: null;
  sector: null;
  timeframe: null;
  year: number | null;
  tags: Array<string> | null;
  heroMedia: {
    kind: "image" | "video";
    alt: string;
    caption: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    videoUrl: string | null;
    lqip: string | null;
  } | null;
  metrics: null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "mediaItem";
    kind: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    videoFile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    videoUrl: string | null;
    poster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt: string;
    caption?: string;
    lqip: string | null;
  }> | null;
  gallery: Array<{
    _key: string;
    kind: "image" | "video";
    alt: string;
    caption: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    videoUrl: string | null;
    lqip: string | null;
  }> | null;
} | null;
// Variable: MUSINGS_INDEX_QUERY
// Query: *[_type == "musing" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    tags  }
export type MUSINGS_INDEX_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string | null;
  tags: Array<string> | null;
}>;
// Variable: MUSING_SLUGS_QUERY
// Query: *[_type == "musing" && defined(slug.current)]{    "slug": slug.current  }
export type MUSING_SLUGS_QUERYResult = Array<{
  slug: string;
}>;
// Variable: MUSING_QUERY
// Query: *[_type == "musing" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    publishedAt,    excerpt,    tags,    body[]{      ...,      _type == "mediaItem" => {        ...,        "videoUrl": coalesce(videoUrl, videoFile.asset->url),        "lqip": image.asset->metadata.lqip      }    }  }
export type MUSING_QUERYResult = {
  _id: string;
  title: string;
  slug: string;
  publishedAt: string | null;
  excerpt: string | null;
  tags: Array<string> | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
    _type: "mediaItem";
    kind: "image" | "video";
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    videoFile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    videoUrl: string | null;
    poster?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    alt: string;
    caption?: string;
    lqip: string | null;
  }> | null;
} | null;
// Variable: INFO_QUERY
// Query: *[_id == "siteSettings"][0]{    title,    intro,    contactEmail,    locations,    social[]{      _key,      label,      url    }  }
export type INFO_QUERYResult = {
  title: string;
  intro: null;
  contactEmail: null;
  locations: null;
  social: null;
} | {
  title: string | null;
  intro: null;
  contactEmail: null;
  locations: null;
  social: null;
} | {
  title: string | null;
  intro: string | null;
  contactEmail: string | null;
  locations: Array<string> | null;
  social: Array<{
    _key: string;
    label: string | null;
    url: string | null;
  }> | null;
} | null;
// Variable: LAYOUT_QUERY
// Query: *[_id == "siteSettings"][0]{    title,    tickerItems,    contactEmail  }
export type LAYOUT_QUERYResult = {
  title: string;
  tickerItems: null;
  contactEmail: null;
} | {
  title: string | null;
  tickerItems: null;
  contactEmail: null;
} | {
  title: string | null;
  tickerItems: Array<string> | null;
  contactEmail: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "{\n  \"settings\": *[_id == \"siteSettings\"][0]{\n    title,\n    intro\n  },\n  \"ordered\": *[_id == \"siteSettings\"][0].gridOrder[]->{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    tags,\n    client,\n    year,\n    \"subtitle\": select(\n      _type == \"caseStudy\" => coalesce(sector, client, role),\n      coalesce(client, description)\n    ),\n    \"summary\": coalesce(standfirst, description),\n    heroMedia{\n      kind,\n      alt,\n      image,\n      poster,\n      \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n      \"lqip\": image.asset->metadata.lqip\n    }\n  },\n  \"extra\": *[\n    (_type == \"caseStudy\" || _type == \"project\")\n    && defined(slug.current)\n    && !(_id in *[_id == \"siteSettings\"][0].gridOrder[]._ref)\n  ] | order(coalesce(order, 100) asc, coalesce(year, 0) desc){\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    tags,\n    client,\n    year,\n    \"subtitle\": select(\n      _type == \"caseStudy\" => coalesce(sector, client, role),\n      coalesce(client, description)\n    ),\n    \"summary\": coalesce(standfirst, description),\n    heroMedia{\n      kind,\n      alt,\n      image,\n      poster,\n      \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n      \"lqip\": image.asset->metadata.lqip\n    }\n  }\n}": HOME_QUERYResult;
    "{\n  \"ordered\": *[_id == \"siteSettings\"][0].gridOrder[]->{\n    _type,\n    title,\n    \"slug\": slug.current\n  },\n  \"extra\": *[\n    (_type == \"caseStudy\" || _type == \"project\")\n    && defined(slug.current)\n    && !(_id in *[_id == \"siteSettings\"][0].gridOrder[]._ref)\n  ] | order(coalesce(order, 100) asc, coalesce(year, 0) desc){\n    _type,\n    title,\n    \"slug\": slug.current\n  }\n}": WORK_ORDER_QUERYResult;
    "\n  *[(_type == \"caseStudy\" || _type == \"project\") && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": WORK_SLUGS_QUERYResult;
    "\n  *[(_type == \"caseStudy\" || _type == \"project\") && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    \"slug\": slug.current,\n    standfirst,\n    description,\n    client,\n    role,\n    sector,\n    timeframe,\n    year,\n    tags,\n    heroMedia{\n      kind,\n      alt,\n      caption,\n      image,\n      poster,\n      \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n      \"lqip\": image.asset->metadata.lqip\n    },\n    metrics[]{\n      _key,\n      value,\n      label,\n      note\n    },\n    body[]{\n      ...,\n      _type == \"mediaItem\" => {\n        ...,\n        \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n        \"lqip\": image.asset->metadata.lqip\n      }\n    },\n    gallery[]{\n      _key,\n      kind,\n      alt,\n      caption,\n      image,\n      poster,\n      \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n      \"lqip\": image.asset->metadata.lqip\n    }\n  }\n": WORK_QUERYResult;
    "\n  *[_type == \"musing\" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    excerpt,\n    publishedAt,\n    tags\n  }\n": MUSINGS_INDEX_QUERYResult;
    "\n  *[_type == \"musing\" && defined(slug.current)]{\n    \"slug\": slug.current\n  }\n": MUSING_SLUGS_QUERYResult;
    "\n  *[_type == \"musing\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    publishedAt,\n    excerpt,\n    tags,\n    body[]{\n      ...,\n      _type == \"mediaItem\" => {\n        ...,\n        \"videoUrl\": coalesce(videoUrl, videoFile.asset->url),\n        \"lqip\": image.asset->metadata.lqip\n      }\n    }\n  }\n": MUSING_QUERYResult;
    "\n  *[_id == \"siteSettings\"][0]{\n    title,\n    intro,\n    contactEmail,\n    locations,\n    social[]{\n      _key,\n      label,\n      url\n    }\n  }\n": INFO_QUERYResult;
    "\n  *[_id == \"siteSettings\"][0]{\n    title,\n    tickerItems,\n    contactEmail\n  }\n": LAYOUT_QUERYResult;
  }
}
